Update to RxSwift 5.1.0
RxSwiftCommunity/RxDataSources pull request #358
Opened 2020-03-17 12:14 UTC by abesuunto

RxSwift 5.1.0 is out and we need to switch to that version.
The main reason is this: https://developer.apple.com/news/?id=12232019b
RxSwift 5.0.x or earlier has a dependency on UIWebView via RxCocoa. 
RxSwift 5.1.0 removes UIWebView dependency.

2020-04-23 09:42 UTC, yourshinsuke commented
Not yet?

2020-04-27 09:45 UTC, yourshinsuke commented
UIWebView - deprecated but found #352

2020-04-27 09:46 UTC, yourshinsuke commented
@RxSwiftCommunity
Did yo give up to maintain the project?

2020-07-23 12:12 UTC, PaulinaRaziunaiteTelesoftas commented
Will it be merged?

2020-09-09 21:11 UTC, Overcot approved these changes

2020-09-18 09:34 UTC, Cedrick84 commented
Hi guys, is this still being worked on? Would love to see this merged.

2020-10-08 10:14 UTC, teameh commented
This looks approved but isn't merged yet. Probably needs rebased an conflicts solved. Pin @abesuunto 🙂

2020-10-08 12:48 UTC, abesuunto commented
Rebased and updated to RxSwift 5.1.1 because of this: https://github.com/ReactiveX/RxSwift/issues/2125

2020-10-08 14:07 UTC, teameh commented
@Overcot LGTM! 😄

2020-10-08 16:03 UTC, abesuunto commented
Ready to merge

2020-11-27 22:53 UTC, mashe requested changes
RxSwift version is not consistent for Carthage, CocoaPods and SPM
I guess Package.resolved file could be omitted.

2020-12-21 16:39 UTC, abesuunto commented
Requested changes have been done.

2021-01-02 09:40 UTC, closed without merging